"""Added genre and publication_year columns to Book model

Revision ID: 380b06634f63
Revises: 
Create Date: 2024-04-22 19:33:08.099791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380b06634f63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('publication_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('publication_year')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
